### PR TITLE
Redesigned plugin code

### PR DESCRIPTION
**Pull request by tank666**
Fixed the problem of endless launch of the plugin if no objects were selected. If text and non-text layers were selected, notifications will appear with the names of the non-text layers and a notification with the number of successfully reset text layer names.

### CODE REVIEW

**Comment by megaroeny** [comment]
Thanks I'll check this out later today/tomorrow! Appreciate it, very unexpected 😄

**Review by megaroeny — COMMENTED** [review]
I'll go through these later today 🙂 I've never had anyone PR on my repos, so I'll have to remember how to review and test with the GitHub desktop app. Thanks again!

**Review by megaroeny — CHANGES_REQUESTED** [review]
Why was this deleted? I prefer to write in typescript, and I'm a beginner at JS. Can you undelete this, thanks!

**Review by megaroeny — COMMENTED** [review]
Why was `code.ts` deleted? I prefer to write in typescript, and I'm a beginner at JS. Can you undelete this, thanks!

**Comment by megaroeny** [comment]
Cherry-picked changes from `code.js`, and copied them over to my `code.ts` file. Thank you, and closing this PR!

**Comment by tank666** [comment]
> Why was `code.ts` deleted?

I looked that code.ts is no different from code.js and thought I could delete it. And this is my first Pull Request, I don't know all the intricacies of the platform.

**Comment by megaroeny** [comment]
> > Why was `code.ts` deleted?
> 
> I looked that code.ts is no different from code.js and thought I could delete it. And this is my first Pull Request, I don't know all the intricacies of the platform.

Ah okay, no problem!👍🏼 Yes Figma API uses typescript and I was getting a comply build error. Thanks so much again. See my tweaks I made too 😊

**Comment by tank666** [comment]
> Ah okay, no problem!👍🏼 Yes Figma API uses typescript and I was getting a comply build error.

Since I did not use VS Code, I immediately wrote in `code.js`, launched the plugin and checked its performance and the presence of errors in the console in the Figma app.

> See my tweaks I made too 😊

Thanks, I looked. Now I will try to update my repository.

**Comment by megaroeny** [comment]
Here's their intro guide to help you get setup 🙂

https://www.figma.com/plugin-docs/setup/

**Comment by tank666** [comment]
Thanks I know. Previously studied the Figma API documentation. I am not using VS Code as unnecessary.

**Pull request closed without merging**
